# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabwidget2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabwidget2.setGeometry(QtCore.QRect(0, 0, 1651, 751))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.tabwidget2.setFont(font)
        self.tabwidget2.setObjectName("tabwidget2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 661, 701))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 57, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setEnabled(True)
        self.horizontalSlider.setGeometry(QtCore.QRect(170, 290, 221, 21))
        self.horizontalSlider.setMinimum(100)
        self.horizontalSlider.setMaximum(3000)
        self.horizontalSlider.setSingleStep(100)
        self.horizontalSlider.setProperty("value", 1500)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_2.setEnabled(True)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(170, 410, 221, 21))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(30)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(60, 540, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 540, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 540, 112, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lcdNumber = QtWidgets.QSpinBox(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(420, 31, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setMinimum(5)
        self.lcdNumber.setMaximum(4000)
        self.lcdNumber.setSingleStep(5)
        self.lcdNumber.setProperty("value", 2000)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QSpinBox(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(420, 140, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setMinimum(5)
        self.lcdNumber_2.setMaximum(4000)
        self.lcdNumber_2.setSingleStep(5)
        self.lcdNumber_2.setProperty("value", 2000)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QSpinBox(self.groupBox)
        self.lcdNumber_3.setGeometry(QtCore.QRect(420, 270, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setMinimum(5)
        self.lcdNumber_3.setMaximum(3000)
        self.lcdNumber_3.setSingleStep(5)
        self.lcdNumber_3.setProperty("value", 1500)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QSpinBox(self.groupBox)
        self.lcdNumber_4.setGeometry(QtCore.QRect(420, 390, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setMinimum(1)
        self.lcdNumber_4.setMaximum(30)
        self.lcdNumber_4.setSingleStep(1)
        self.lcdNumber_4.setProperty("value", 1)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(190, 20, 160, 191))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dial = QtWidgets.QDial(self.verticalLayoutWidget_4)
        self.dial.setEnabled(True)
        self.dial.setMinimum(100)
        self.dial.setMaximum(4000)
        self.dial.setSingleStep(100)
        self.dial.setProperty("value", 2000)
        self.dial.setObjectName("dial")
        self.verticalLayout_5.addWidget(self.dial)
        self.dial_2 = QtWidgets.QDial(self.verticalLayoutWidget_4)
        self.dial_2.setEnabled(True)
        self.dial_2.setMinimum(100)
        self.dial_2.setMaximum(4000)
        self.dial_2.setSingleStep(100)
        self.dial_2.setProperty("value", 2000)
        self.dial_2.setObjectName("dial_2")
        self.verticalLayout_5.addWidget(self.dial_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(690, 20, 461, 691))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(100, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName("spinBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setGeometry(QtCore.QRect(120, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMaximum(15)
        self.spinBox_2.setProperty("value", 15)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(50, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(50, 270, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(50, 320, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(50, 370, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 200, 86, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdb1_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb1_start.setFont(font)
        self.rdb1_start.setObjectName("rdb1_start")
        self.verticalLayout.addWidget(self.rdb1_start)
        self.rdb2_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb2_start.setFont(font)
        self.rdb2_start.setObjectName("rdb2_start")
        self.verticalLayout.addWidget(self.rdb2_start)
        self.rdb3_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb3_start.setFont(font)
        self.rdb3_start.setObjectName("rdb3_start")
        self.verticalLayout.addWidget(self.rdb3_start)
        self.rdb4_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb4_start.setFont(font)
        self.rdb4_start.setObjectName("rdb4_start")
        self.verticalLayout.addWidget(self.rdb4_start)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(320, 200, 86, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rdb1_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb1_end.setFont(font)
        self.rdb1_end.setObjectName("rdb1_end")
        self.verticalLayout_2.addWidget(self.rdb1_end)
        self.rdb2_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb2_end.setFont(font)
        self.rdb2_end.setObjectName("rdb2_end")
        self.verticalLayout_2.addWidget(self.rdb2_end)
        self.rdb3_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb3_end.setFont(font)
        self.rdb3_end.setObjectName("rdb3_end")
        self.verticalLayout_2.addWidget(self.rdb3_end)
        self.rdb4_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb4_end.setFont(font)
        self.rdb4_end.setObjectName("rdb4_end")
        self.verticalLayout_2.addWidget(self.rdb4_end)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(171, 180, 101, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(310, 180, 101, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.rdb_exec = QtWidgets.QPushButton(self.groupBox_2)
        self.rdb_exec.setGeometry(QtCore.QRect(30, 440, 101, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.rdb_exec.setFont(font)
        self.rdb_exec.setObjectName("rdb_exec")
        self.rdb_clean = QtWidgets.QPushButton(self.groupBox_2)
        self.rdb_clean.setGeometry(QtCore.QRect(180, 440, 111, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.rdb_clean.setFont(font)
        self.rdb_clean.setObjectName("rdb_clean")
        self.rdc_absorb = QtWidgets.QPushButton(self.groupBox_2)
        self.rdc_absorb.setGeometry(QtCore.QRect(330, 440, 111, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.rdc_absorb.setFont(font)
        self.rdc_absorb.setObjectName("rdc_absorb")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(210, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setGeometry(QtCore.QRect(340, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setMaximum(15)
        self.spinBox_3.setProperty("value", 1)
        self.spinBox_3.setObjectName("spinBox_3")
        self.tabwidget2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Data_look = QtWidgets.QPushButton(self.tab_2)
        self.Data_look.setGeometry(QtCore.QRect(490, 0, 101, 41))
        self.Data_look.setObjectName("Data_look")
        self.Data_R_search = QtWidgets.QPushButton(self.tab_2)
        self.Data_R_search.setGeometry(QtCore.QRect(200, 60, 151, 41))
        self.Data_R_search.setObjectName("Data_R_search")
        self.Data_N_search = QtWidgets.QPushButton(self.tab_2)
        self.Data_N_search.setGeometry(QtCore.QRect(200, 120, 151, 41))
        self.Data_N_search.setObjectName("Data_N_search")
        self.Data_reaction = QtWidgets.QPushButton(self.tab_2)
        self.Data_reaction.setGeometry(QtCore.QRect(570, 60, 171, 41))
        self.Data_reaction.setObjectName("Data_reaction")
        self.Datatable = QtWidgets.QTableWidget(self.tab_2)
        self.Datatable.setGeometry(QtCore.QRect(60, 190, 1021, 241))
        self.Datatable.setObjectName("Datatable")
        self.Datatable.setColumnCount(0)
        self.Datatable.setRowCount(0)
        self.Data_R_tx = QtWidgets.QLineEdit(self.tab_2)
        self.Data_R_tx.setGeometry(QtCore.QRect(360, 60, 141, 41))
        self.Data_R_tx.setToolTip("")
        self.Data_R_tx.setObjectName("Data_R_tx")
        self.Data_N_tv = QtWidgets.QLineEdit(self.tab_2)
        self.Data_N_tv.setGeometry(QtCore.QRect(360, 120, 141, 41))
        self.Data_N_tv.setObjectName("Data_N_tv")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(760, 60, 131, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.N_peizhi = QtWidgets.QPushButton(self.tab_2)
        self.N_peizhi.setGeometry(QtCore.QRect(140, 480, 201, 41))
        self.N_peizhi.setObjectName("N_peizhi")
        self.Data_peizhi = QtWidgets.QLineEdit(self.tab_2)
        self.Data_peizhi.setGeometry(QtCore.QRect(360, 480, 141, 41))
        self.Data_peizhi.setText("")
        self.Data_peizhi.setObjectName("Data_peizhi")
        self.react1 = QtWidgets.QLabel(self.tab_2)
        self.react1.setGeometry(QtCore.QRect(610, 510, 91, 31))
        self.react1.setObjectName("react1")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(710, 460, 91, 31))
        self.label_16.setObjectName("label_16")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(700, 500, 91, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.req1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.req1.setObjectName("req1")
        self.verticalLayout_3.addWidget(self.req1)
        self.req2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.req2.setObjectName("req2")
        self.verticalLayout_3.addWidget(self.req2)
        self.req3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.req3.setObjectName("req3")
        self.verticalLayout_3.addWidget(self.req3)
        self.req4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.req4.setObjectName("req4")
        self.verticalLayout_3.addWidget(self.req4)
        self.react2 = QtWidgets.QLabel(self.tab_2)
        self.react2.setGeometry(QtCore.QRect(610, 550, 91, 31))
        self.react2.setObjectName("react2")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(610, 600, 91, 31))
        self.label_19.setObjectName("label_19")
        self.react4 = QtWidgets.QLabel(self.tab_2)
        self.react4.setGeometry(QtCore.QRect(610, 640, 91, 31))
        self.react4.setObjectName("react4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(810, 500, 61, 191))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pump1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.pump1.setObjectName("pump1")
        self.verticalLayout_6.addWidget(self.pump1)
        self.pump2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.pump2.setObjectName("pump2")
        self.verticalLayout_6.addWidget(self.pump2)
        self.pump3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.pump3.setObjectName("pump3")
        self.verticalLayout_6.addWidget(self.pump3)
        self.own4_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.own4_2.setObjectName("own4_2")
        self.verticalLayout_6.addWidget(self.own4_2)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(810, 460, 91, 31))
        self.label_18.setObjectName("label_18")
        self.Data_added = QtWidgets.QPushButton(self.tab_2)
        self.Data_added.setGeometry(QtCore.QRect(570, 120, 171, 41))
        self.Data_added.setObjectName("Data_added")
        self.pb_fill = QtWidgets.QPushButton(self.tab_2)
        self.pb_fill.setGeometry(QtCore.QRect(140, 540, 141, 41))
        self.pb_fill.setObjectName("pb_fill")
        self.pb_mix = QtWidgets.QPushButton(self.tab_2)
        self.pb_mix.setGeometry(QtCore.QRect(310, 540, 121, 41))
        self.pb_mix.setObjectName("pb_mix")
        self.tabwidget2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.exec_spec = QtWidgets.QPushButton(self.tab_3)
        self.exec_spec.setGeometry(QtCore.QRect(80, 60, 131, 61))
        self.exec_spec.setObjectName("exec_spec")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(80, 190, 961, 491))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("G:/图库/11-17-01-90-7.jpg"))
        self.label_13.setObjectName("label_13")
        self.tabwidget2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 340, 201, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(430, 340, 191, 71))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(149, 460, 841, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(410, 180, 222, 61))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(160, 170, 223, 71))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_4.setGeometry(QtCore.QRect(170, 250, 201, 61))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(100)
        self.spinBox_4.setSingleStep(1)
        self.spinBox_4.setProperty("value", 6)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_5.setGeometry(QtCore.QRect(430, 250, 191, 61))
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setMaximum(100)
        self.spinBox_5.setSingleStep(1)
        self.spinBox_5.setProperty("value", 6)
        self.spinBox_5.setObjectName("spinBox_5")
        self.tabwidget2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 0, 421, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setWordWrap(False)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(20, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 270, 112, 34))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(140, 270, 112, 34))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_12.setGeometry(QtCore.QRect(280, 270, 112, 34))
        self.pushButton_12.setObjectName("pushButton_12")
        self.lcdNumber_5 = QtWidgets.QSpinBox(self.groupBox_3)
        self.lcdNumber_5.setGeometry(QtCore.QRect(260, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setMinimum(5)
        self.lcdNumber_5.setMaximum(4000)
        self.lcdNumber_5.setSingleStep(5)
        self.lcdNumber_5.setProperty("value", 2000)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QSpinBox(self.groupBox_3)
        self.lcdNumber_6.setGeometry(QtCore.QRect(260, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setMinimum(5)
        self.lcdNumber_6.setMaximum(4000)
        self.lcdNumber_6.setSingleStep(5)
        self.lcdNumber_6.setProperty("value", 2000)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QSpinBox(self.groupBox_3)
        self.lcdNumber_7.setGeometry(QtCore.QRect(260, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setMinimum(5)
        self.lcdNumber_7.setMaximum(3000)
        self.lcdNumber_7.setSingleStep(5)
        self.lcdNumber_7.setProperty("value", 1500)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QSpinBox(self.groupBox_3)
        self.lcdNumber_8.setGeometry(QtCore.QRect(260, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_8.setFont(font)
        self.lcdNumber_8.setMinimum(1)
        self.lcdNumber_8.setMaximum(30)
        self.lcdNumber_8.setSingleStep(1)
        self.lcdNumber_8.setProperty("value", 1)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(500, 0, 421, 331))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_25.setWordWrap(False)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(20, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(20, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 270, 112, 34))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_14.setGeometry(QtCore.QRect(140, 270, 112, 34))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_15.setGeometry(QtCore.QRect(280, 270, 112, 34))
        self.pushButton_15.setObjectName("pushButton_15")
        self.lcdNumber_9 = QtWidgets.QSpinBox(self.groupBox_4)
        self.lcdNumber_9.setGeometry(QtCore.QRect(260, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_9.setFont(font)
        self.lcdNumber_9.setMinimum(5)
        self.lcdNumber_9.setMaximum(4000)
        self.lcdNumber_9.setSingleStep(5)
        self.lcdNumber_9.setProperty("value", 2000)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QSpinBox(self.groupBox_4)
        self.lcdNumber_10.setGeometry(QtCore.QRect(260, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_10.setFont(font)
        self.lcdNumber_10.setMinimum(5)
        self.lcdNumber_10.setMaximum(4000)
        self.lcdNumber_10.setSingleStep(5)
        self.lcdNumber_10.setProperty("value", 2000)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_11 = QtWidgets.QSpinBox(self.groupBox_4)
        self.lcdNumber_11.setGeometry(QtCore.QRect(260, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_11.setFont(font)
        self.lcdNumber_11.setMinimum(5)
        self.lcdNumber_11.setMaximum(3000)
        self.lcdNumber_11.setSingleStep(5)
        self.lcdNumber_11.setProperty("value", 1500)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_12 = QtWidgets.QSpinBox(self.groupBox_4)
        self.lcdNumber_12.setGeometry(QtCore.QRect(260, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_12.setFont(font)
        self.lcdNumber_12.setMinimum(1)
        self.lcdNumber_12.setMaximum(30)
        self.lcdNumber_12.setSingleStep(1)
        self.lcdNumber_12.setProperty("value", 1)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 340, 421, 331))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_28.setWordWrap(False)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setWordWrap(False)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(20, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(20, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 270, 112, 34))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_17.setGeometry(QtCore.QRect(140, 270, 112, 34))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_18.setGeometry(QtCore.QRect(280, 270, 112, 34))
        self.pushButton_18.setObjectName("pushButton_18")
        self.lcdNumber_13 = QtWidgets.QSpinBox(self.groupBox_5)
        self.lcdNumber_13.setGeometry(QtCore.QRect(260, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_13.setFont(font)
        self.lcdNumber_13.setMinimum(5)
        self.lcdNumber_13.setMaximum(4000)
        self.lcdNumber_13.setSingleStep(5)
        self.lcdNumber_13.setProperty("value", 2000)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_14 = QtWidgets.QSpinBox(self.groupBox_5)
        self.lcdNumber_14.setGeometry(QtCore.QRect(260, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_14.setFont(font)
        self.lcdNumber_14.setMinimum(5)
        self.lcdNumber_14.setMaximum(4000)
        self.lcdNumber_14.setSingleStep(5)
        self.lcdNumber_14.setProperty("value", 2000)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.lcdNumber_15 = QtWidgets.QSpinBox(self.groupBox_5)
        self.lcdNumber_15.setGeometry(QtCore.QRect(260, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_15.setFont(font)
        self.lcdNumber_15.setMinimum(5)
        self.lcdNumber_15.setMaximum(3000)
        self.lcdNumber_15.setSingleStep(5)
        self.lcdNumber_15.setProperty("value", 1500)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_16 = QtWidgets.QSpinBox(self.groupBox_5)
        self.lcdNumber_16.setGeometry(QtCore.QRect(260, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_16.setFont(font)
        self.lcdNumber_16.setMinimum(1)
        self.lcdNumber_16.setMaximum(30)
        self.lcdNumber_16.setSingleStep(1)
        self.lcdNumber_16.setProperty("value", 1)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(500, 340, 421, 331))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_32 = QtWidgets.QLabel(self.groupBox_6)
        self.label_32.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setTextFormat(QtCore.Qt.AutoText)
        self.label_32.setWordWrap(False)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setTextFormat(QtCore.Qt.AutoText)
        self.label_33.setWordWrap(False)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setGeometry(QtCore.QRect(20, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setGeometry(QtCore.QRect(20, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 270, 112, 34))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_20.setGeometry(QtCore.QRect(140, 270, 112, 34))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_21.setGeometry(QtCore.QRect(280, 270, 112, 34))
        self.pushButton_21.setObjectName("pushButton_21")
        self.lcdNumber_17 = QtWidgets.QSpinBox(self.groupBox_6)
        self.lcdNumber_17.setGeometry(QtCore.QRect(260, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_17.setFont(font)
        self.lcdNumber_17.setMinimum(5)
        self.lcdNumber_17.setMaximum(4000)
        self.lcdNumber_17.setSingleStep(5)
        self.lcdNumber_17.setProperty("value", 2000)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.lcdNumber_18 = QtWidgets.QSpinBox(self.groupBox_6)
        self.lcdNumber_18.setGeometry(QtCore.QRect(260, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_18.setFont(font)
        self.lcdNumber_18.setMinimum(5)
        self.lcdNumber_18.setMaximum(4000)
        self.lcdNumber_18.setSingleStep(5)
        self.lcdNumber_18.setProperty("value", 2000)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.lcdNumber_19 = QtWidgets.QSpinBox(self.groupBox_6)
        self.lcdNumber_19.setGeometry(QtCore.QRect(260, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_19.setFont(font)
        self.lcdNumber_19.setMinimum(5)
        self.lcdNumber_19.setMaximum(3000)
        self.lcdNumber_19.setSingleStep(5)
        self.lcdNumber_19.setProperty("value", 1500)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.lcdNumber_20 = QtWidgets.QSpinBox(self.groupBox_6)
        self.lcdNumber_20.setGeometry(QtCore.QRect(260, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.lcdNumber_20.setFont(font)
        self.lcdNumber_20.setMinimum(1)
        self.lcdNumber_20.setMaximum(30)
        self.lcdNumber_20.setSingleStep(1)
        self.lcdNumber_20.setProperty("value", 1)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.tabwidget2.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabwidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabwidget2.setToolTip(_translate("MainWindow", "<html><head/><body><p>光谱分许</p></body></html>"))
        self.tabwidget2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "指令发送"))
        self.label.setText(_translate("MainWindow", "抽取速度"))
        self.label_2.setText(_translate("MainWindow", "排出速度"))
        self.label_3.setText(_translate("MainWindow", "抽取体积"))
        self.label_4.setText(_translate("MainWindow", "循环次数"))
        self.pushButton.setText(_translate("MainWindow", "初始化"))
        self.pushButton_2.setText(_translate("MainWindow", "停止"))
        self.pushButton_3.setText(_translate("MainWindow", "执行"))
        self.groupBox_2.setTitle(_translate("MainWindow", "泵切换与端口控制"))
        self.label_5.setText(_translate("MainWindow", "泵编号"))
        self.label_6.setText(_translate("MainWindow", "泵端口号"))
        self.label_7.setText(_translate("MainWindow", "蠕动泵1"))
        self.label_8.setText(_translate("MainWindow", "蠕动泵2"))
        self.label_9.setText(_translate("MainWindow", "蠕动泵3"))
        self.label_10.setText(_translate("MainWindow", "蠕动泵4"))
        self.label_11.setText(_translate("MainWindow", "开始时间(s)"))
        self.label_12.setText(_translate("MainWindow", "结束时间(s)"))
        self.rdb_exec.setText(_translate("MainWindow", "执行"))
        self.rdb_clean.setText(_translate("MainWindow", "清洗"))
        self.rdc_absorb.setText(_translate("MainWindow", "测吸收基线"))
        self.label_14.setText(_translate("MainWindow", "蠕动泵端口号"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab), _translate("MainWindow", "手动调试"))
        self.Data_look.setText(_translate("MainWindow", "查看数据库"))
        self.Data_R_search.setText(_translate("MainWindow", "按反应物查找数据"))
        self.Data_N_search.setText(_translate("MainWindow", "按编号查找数据"))
        self.Data_reaction.setText(_translate("MainWindow", "执行反应（按编号）"))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>按编号</p></body></html>"))
        self.N_peizhi.setText(_translate("MainWindow", "配置溶液（输入编号）"))
        self.react1.setText(_translate("MainWindow", "反应物1"))
        self.label_16.setText(_translate("MainWindow", "要求浓度"))
        self.req4.setText(_translate("MainWindow", "Water"))
        self.react2.setText(_translate("MainWindow", "反应物2"))
        self.label_19.setText(_translate("MainWindow", "反应物3"))
        self.react4.setText(_translate("MainWindow", "反应物4"))
        self.pump1.setText(_translate("MainWindow", "2"))
        self.pump2.setText(_translate("MainWindow", "3"))
        self.pump3.setText(_translate("MainWindow", "4"))
        self.own4_2.setText(_translate("MainWindow", "1"))
        self.label_18.setText(_translate("MainWindow", "泵编号"))
        self.Data_added.setText(_translate("MainWindow", "文献添加数据"))
        self.pb_fill.setText(_translate("MainWindow", "注满管道"))
        self.pb_mix.setText(_translate("MainWindow", "开始混合"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab_2), _translate("MainWindow", "数据库"))
        self.exec_spec.setText(_translate("MainWindow", "光谱图"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab_3), _translate("MainWindow", "光谱分析"))
        self.pushButton_8.setText(_translate("MainWindow", "打开抽取速度文件"))
        self.pushButton_9.setText(_translate("MainWindow", "打开排出速度文件"))
        self.pushButton_5.setText(_translate("MainWindow", "初始化"))
        self.pushButton_4.setText(_translate("MainWindow", "抽取"))
        self.pushButton_6.setText(_translate("MainWindow", "排出"))
        self.pushButton_7.setText(_translate("MainWindow", "停止"))
        self.label_17.setText(_translate("MainWindow", "排出时的路径数量"))
        self.label_15.setText(_translate("MainWindow", "抽取时的路径数量"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab_4), _translate("MainWindow", "变速模式"))
        self.groupBox_3.setTitle(_translate("MainWindow", "泵1"))
        self.label_20.setText(_translate("MainWindow", "抽取速度"))
        self.label_21.setText(_translate("MainWindow", "排出速度"))
        self.label_22.setText(_translate("MainWindow", "抽取体积"))
        self.label_23.setText(_translate("MainWindow", "循环次数"))
        self.pushButton_10.setText(_translate("MainWindow", "初始化"))
        self.pushButton_11.setText(_translate("MainWindow", "停止"))
        self.pushButton_12.setText(_translate("MainWindow", "执行"))
        self.groupBox_4.setTitle(_translate("MainWindow", "泵2"))
        self.label_24.setText(_translate("MainWindow", "抽取速度"))
        self.label_25.setText(_translate("MainWindow", "排出速度"))
        self.label_26.setText(_translate("MainWindow", "抽取体积"))
        self.label_27.setText(_translate("MainWindow", "循环次数"))
        self.pushButton_13.setText(_translate("MainWindow", "初始化"))
        self.pushButton_14.setText(_translate("MainWindow", "停止"))
        self.pushButton_15.setText(_translate("MainWindow", "执行"))
        self.groupBox_5.setTitle(_translate("MainWindow", "泵3"))
        self.label_28.setText(_translate("MainWindow", "抽取速度"))
        self.label_29.setText(_translate("MainWindow", "排出速度"))
        self.label_30.setText(_translate("MainWindow", "抽取体积"))
        self.label_31.setText(_translate("MainWindow", "循环次数"))
        self.pushButton_16.setText(_translate("MainWindow", "初始化"))
        self.pushButton_17.setText(_translate("MainWindow", "停止"))
        self.pushButton_18.setText(_translate("MainWindow", "执行"))
        self.groupBox_6.setTitle(_translate("MainWindow", "泵4"))
        self.label_32.setText(_translate("MainWindow", "抽取速度"))
        self.label_33.setText(_translate("MainWindow", "排出速度"))
        self.label_34.setText(_translate("MainWindow", "抽取体积"))
        self.label_35.setText(_translate("MainWindow", "循环次数"))
        self.pushButton_19.setText(_translate("MainWindow", "初始化"))
        self.pushButton_20.setText(_translate("MainWindow", "停止"))
        self.pushButton_21.setText(_translate("MainWindow", "执行"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab_5), _translate("MainWindow", "并列显示模式"))

